/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Timetable;
import javax.swing.JOptionPane;
import java.awt.event.WindowEvent;
/**
 *
 * @author Ayush
 */
public class L_ogin extends javax.swing.JFrame {

    
    public L_ogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelUse = new javax.swing.JLabel();
        jLabelPas = new javax.swing.JLabel();
        jButtonLogi = new javax.swing.JButton();
        jButtonRese = new javax.swing.JButton();
        jButtonExi = new javax.swing.JButton();
        jTextUsernam = new javax.swing.JTextField();
        jPasswor = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Login Systems");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));

        jLabelUse.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelUse.setText("Username  :");

        jLabelPas.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelPas.setText("Password  :");

        jButtonLogi.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonLogi.setText("Login");
        jButtonLogi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogiActionPerformed(evt);
            }
        });

        jButtonRese.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonRese.setText("Reset");
        jButtonRese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReseActionPerformed(evt);
            }
        });

        jButtonExi.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonExi.setText("Exit");
        jButtonExi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExiActionPerformed(evt);
            }
        });

        jTextUsernam.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        jPasswor.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jPasswor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassworActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPas)
                            .addComponent(jLabelUse))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswor, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextUsernam, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonLogi)
                        .addGap(49, 49, 49)
                        .addComponent(jButtonRese)
                        .addGap(71, 71, 71)
                        .addComponent(jButtonExi)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUse)
                    .addComponent(jTextUsernam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPas))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogi)
                    .addComponent(jButtonRese)
                    .addComponent(jButtonExi))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogiActionPerformed
        // TODO add your handling code here:
        String password = jPasswor.getText();
        String username = jTextUsernam.getText();
        if(password.contains("ayush") && (username.contains("Ayush")))
        {
            jTextUsernam.setText(null);
            jPasswor.setText(null);
            systemExit();
           TimeTable ph= new TimeTable();
            ph.setVisible(true);

        }
        else
        {
            JOptionPane.showMessageDialog(null,"Incvalid login Details","Login Error",JOptionPane.ERROR_MESSAGE);
            jPasswor.setText(null);
            jTextUsernam.setText(null);
        }
    }//GEN-LAST:event_jButtonLogiActionPerformed

    private void jButtonReseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReseActionPerformed
        // TODO add your handling code here:
        jPasswor.setText(null);
        jTextUsernam.setText(null);
    }//GEN-LAST:event_jButtonReseActionPerformed

    private void jButtonExiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExiActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonExiActionPerformed

    private void jPassworActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassworActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassworActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(L_ogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(L_ogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(L_ogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(L_ogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new L_ogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExi;
    private javax.swing.JButton jButtonLogi;
    private javax.swing.JButton jButtonRese;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPas;
    private javax.swing.JLabel jLabelUse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswor;
    private javax.swing.JTextField jTextUsernam;
    // End of variables declaration//GEN-END:variables


private void systemExit()
{
    WindowEvent winClosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
}
}
