/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Timetable;

import javax.swing.JOptionPane;


/**
 *     
 * @author Ayush
 */
public class TimeTable extends javax.swing.JFrame {

double hour1, hour2, hour3, hour4, hour5, hour6, hour7, hour8, hour9, hour10, hour11, hour12, hour13, hour14, hour15, hour16, hour17, hour18, hour19;
double hour20, hour21, hour22, hour23, hour24, hour25, hour26, hour27, hour28, hour29, hour30, hour31, hour32, hour33, hour34, hour35, hour36, hour37, hour38, hour39, hour40;
double hour41, hour42, hour43, hour44, hour45, hour46, hour47, hour48, hour49, hour50, hour51, hour52, hour53, hour54, hour55, hour56, hour57, hour58, hour59, hour60, hour61;
double hour62, hour63, hour64, hour65, hour66, hour67, hour68, hour69, hour70, hour71, hour72, hour73, hour74, hour75, hour76, hour77, hour78, hour79, hour80, hour81, hour82;
double hour83, hour84, hour85, hour86, hour87, hour88, hour89, hour90, hour91, hour92, hour93, hour94, hour95, hour96, hour97; 


double Totalhour1, Totalhour2, Totalhour3, Totalhour4, Totalhour5, Totalhour6, Totalhour7, Totalhour8, Totalhour9, Totalhour10, Totalhour11, Totalhour12, Totalhour13;
double Totalhour14, Totalhour15, Totalhour16, Totalhour17, Totalhour18, Totalhour19, Totalhour20, Totalhour21, Totalhour22, Totalhour23, Totalhour24, Totalhour25, Totalhour26, Totalhour27;
double Totalhour28, Totalhour29, Totalhour30, Totalhour31, Totalhour32, Totalhour33, Totalhour34, Totalhour35, Totalhour36, Totalhour37, Totalhour38, Totalhour39, Totalhour40, Totalhour41;
double Totalhour42, Totalhour43, Totalhour44, Totalhour45, Totalhour46, Totalhour47, Totalhour48, Totalhour49; 
    
    public TimeTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jHW3 = new javax.swing.JLabel();
        jHW1 = new javax.swing.JLabel();
        jHW2 = new javax.swing.JLabel();
        jHW4 = new javax.swing.JLabel();
        jHW5 = new javax.swing.JLabel();
        jMon3 = new javax.swing.JLabel();
        jMon1 = new javax.swing.JLabel();
        jMon2 = new javax.swing.JLabel();
        jMon4 = new javax.swing.JLabel();
        jMon5 = new javax.swing.JLabel();
        jTue5 = new javax.swing.JLabel();
        jTue4 = new javax.swing.JLabel();
        jTue3 = new javax.swing.JLabel();
        jTue2 = new javax.swing.JLabel();
        jTue1 = new javax.swing.JLabel();
        jWed5 = new javax.swing.JLabel();
        jWed4 = new javax.swing.JLabel();
        jWed3 = new javax.swing.JLabel();
        jWed2 = new javax.swing.JLabel();
        jWed1 = new javax.swing.JLabel();
        jThru5 = new javax.swing.JLabel();
        jThru4 = new javax.swing.JLabel();
        jThru3 = new javax.swing.JLabel();
        jThru2 = new javax.swing.JLabel();
        jThru1 = new javax.swing.JLabel();
        jFri4 = new javax.swing.JLabel();
        jFri5 = new javax.swing.JLabel();
        jFri3 = new javax.swing.JLabel();
        jFri2 = new javax.swing.JLabel();
        jFri1 = new javax.swing.JLabel();
        jWages4 = new javax.swing.JLabel();
        jWages5 = new javax.swing.JLabel();
        jWages3 = new javax.swing.JLabel();
        jWages2 = new javax.swing.JLabel();
        jWages1 = new javax.swing.JLabel();
        jHRate1 = new javax.swing.JComboBox<>();
        jHRate2 = new javax.swing.JComboBox<>();
        jHRate5 = new javax.swing.JComboBox<>();
        jHRate3 = new javax.swing.JComboBox<>();
        jHRate4 = new javax.swing.JComboBox<>();
        jOverTime1 = new javax.swing.JComboBox<>();
        jOverTime5 = new javax.swing.JComboBox<>();
        jOverTime4 = new javax.swing.JComboBox<>();
        jOverTime3 = new javax.swing.JComboBox<>();
        jOverTime2 = new javax.swing.JComboBox<>();
        jRadMon = new javax.swing.JRadioButton();
        jRadWed = new javax.swing.JRadioButton();
        jRadTue = new javax.swing.JRadioButton();
        jRadThru = new javax.swing.JRadioButton();
        jRadFri = new javax.swing.JRadioButton();
        jlblWages = new javax.swing.JLabel();
        jTimeIn1 = new javax.swing.JTextField();
        jTimeIn2 = new javax.swing.JTextField();
        jTimeIn4 = new javax.swing.JTextField();
        jTimeIn3 = new javax.swing.JTextField();
        jTimeIn5 = new javax.swing.JTextField();
        jTimeOut1 = new javax.swing.JTextField();
        jTimeOut3 = new javax.swing.JTextField();
        jTimeOut4 = new javax.swing.JTextField();
        jTimeOut2 = new javax.swing.JTextField();
        jTimeOut5 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1366, 788));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Total");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jButton1)
                .addGap(56, 56, 56)
                .addComponent(jButton2)
                .addGap(58, 58, 58)
                .addComponent(jButton3)
                .addContainerGap(601, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Emp Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Time In");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Time Out");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Hrs Rate");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Over Time");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Hrs Wknd");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("AVM");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("DEV");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("SHUBH");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("AKASH");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("AYUSH");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jHW3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jHW3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jHW1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jHW1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jHW2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jHW2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jHW4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jHW4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jHW5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jHW5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jMon3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMon3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jMon1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMon1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jMon2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMon2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jMon4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMon4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jMon5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMon5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTue5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTue5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTue4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTue4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTue3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTue3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTue2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTue2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTue1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTue1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jWed5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jWed5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jWed4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jWed4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jWed3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jWed3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jWed2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jWed2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jWed1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jWed1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jThru5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jThru5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jThru4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jThru4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jThru3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jThru3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jThru2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jThru2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jThru1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jThru1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jFri4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jFri4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jFri5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jFri5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jFri3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jFri3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jFri2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jFri2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jFri1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jFri1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jWages4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jWages4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jWages5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jWages5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jWages3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jWages3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jWages2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jWages2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jWages1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jWages1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jHRate1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jHRate1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "6.90", "8.40", "9.90", "11.40", "12.90" }));

        jHRate2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jHRate2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "6.90", "8.40", "9.90", "11.40", "12.90", " " }));

        jHRate5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jHRate5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "6.90", "8.40", "9.90", "11.40", "12.90" }));

        jHRate3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jHRate3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "6.90", "8.40", "9.90", "11.40", "12.90" }));

        jHRate4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jHRate4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "6.90", "8.40", "9.90", "11.40", "12.90", " " }));
        jHRate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHRate4ActionPerformed(evt);
            }
        });

        jOverTime1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jOverTime1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));

        jOverTime5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jOverTime5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));

        jOverTime4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jOverTime4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));

        jOverTime3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jOverTime3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));

        jOverTime2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jOverTime2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));

        jRadMon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadMon.setText("Mon");
        jRadMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadMonActionPerformed(evt);
            }
        });

        jRadWed.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadWed.setText("Wed");
        jRadWed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadWedActionPerformed(evt);
            }
        });

        jRadTue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadTue.setText("Tue");
        jRadTue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadTueActionPerformed(evt);
            }
        });

        jRadThru.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadThru.setText("Thru");
        jRadThru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadThruActionPerformed(evt);
            }
        });

        jRadFri.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadFri.setText("Fri");
        jRadFri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadFriActionPerformed(evt);
            }
        });

        jlblWages.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblWages.setText("Wages");

        jTimeIn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTimeIn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTimeIn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTimeIn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTimeIn4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTimeIn4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTimeIn3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTimeIn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTimeIn5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTimeIn5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTimeOut1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTimeOut1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTimeOut3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTimeOut3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTimeOut4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTimeOut4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTimeOut2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTimeOut2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTimeOut5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTimeOut5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setText("Working Time Table");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel1)
                                        .addGap(35, 35, 35))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(31, 31, 31)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTimeIn5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTimeIn4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTimeIn2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTimeIn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                            .addComponent(jTimeIn3, javax.swing.GroupLayout.Alignment.LEADING))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jTimeOut3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTimeOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTimeOut2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTimeOut4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTimeOut5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jHRate4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jHRate3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jHRate2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jHRate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jHRate5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jOverTime3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jOverTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jOverTime5, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jOverTime2, javax.swing.GroupLayout.Alignment.LEADING, 0, 67, Short.MAX_VALUE)
                                        .addComponent(jOverTime4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jHW2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jHW4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jHW3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jHW5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jHW1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6))))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jMon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jMon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jMon3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jMon4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jMon5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTue4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTue3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTue2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTue1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTue5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jRadMon, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadTue, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jWed3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jWed2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jWed1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jWed5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jWed4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadWed, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadThru, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jThru4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jThru3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jThru2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jThru1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jThru5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jFri4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jFri3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jFri2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jFri1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jFri5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jRadFri, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jWages4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jWages3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jWages2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jWages1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jWages5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jlblWages)))))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel12)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jRadMon)
                        .addComponent(jRadWed)
                        .addComponent(jRadTue)
                        .addComponent(jRadThru)
                        .addComponent(jRadFri)
                        .addComponent(jlblWages)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(jTimeIn1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(jTimeIn2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTimeIn3)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jTimeIn4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTimeIn5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTimeOut5)
                            .addComponent(jOverTime5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jHRate4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTimeOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jHRate1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jHRate2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jOverTime4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jHRate3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTimeOut2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTimeOut3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTimeOut4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jMon1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jMon2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jMon3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jMon4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTue1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTue2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTue3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTue4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTue5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jHW1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jHW2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jHW3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jHW4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jHW5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jMon5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jHRate5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jOverTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jOverTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(11, 11, 11)
                                    .addComponent(jOverTime3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jWed1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jWed2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jWed3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jWed4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jWed5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jFri1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jFri2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jFri3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jFri4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jFri5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jWages1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jWages2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jWages3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jWages4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jWages5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jThru1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jThru2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jThru3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jThru4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jThru5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadMonActionPerformed

    private void jRadWedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadWedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadWedActionPerformed

    private void jRadTueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadTueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadTueActionPerformed

    private void jRadThruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadThruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadThruActionPerformed

    private void jRadFriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadFriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadFriActionPerformed

    private void jHRate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHRate4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHRate4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jMon1.setText(" ");
        jMon2.setText(" ");
        jMon3.setText(" ");
        jMon4.setText(" ");
        jMon5.setText(" ");
        
        jTue1.setText(" ");
        jTue2.setText(" ");
        jTue3.setText(" ");
        jTue4.setText(" ");
        jTue5.setText(" ");
        
        jWed1.setText(" ");
        jWed2.setText(" ");
        jWed3.setText(" ");
        jWed4.setText(" ");
        jWed5.setText(" ");
        
        jThru1.setText(" ");
        jThru2.setText(" ");
        jThru3.setText(" ");
        jThru4.setText(" ");
        jThru5.setText(" ");
        
        jFri1.setText(" ");
        jFri2.setText(" ");
        jFri3.setText(" ");
        jFri4.setText(" ");
        jFri5.setText(" ");
        
        jTimeIn1.setText(null);
        jTimeIn2.setText(null);
        jTimeIn3.setText(null);
        jTimeIn4.setText(null);
        jTimeIn5.setText(null);
        
        jTimeOut1.setText(null);
        jTimeOut2.setText(null);
        jTimeOut3.setText(null);
        jTimeOut4.setText(null);
        jTimeOut5.setText(null);
        
        jHW1.setText(null);
        jHW2.setText(null);
        jHW3.setText(null);
        jHW4.setText(null);
        jHW5.setText(null);
        
        jWages1.setText(null);
        jWages2.setText(null);
        jWages3.setText(null);
        jWages4.setText(null);
        jWages5.setText(null);
        
        jHRate1.setSelectedIndex(0);
        jHRate2.setSelectedIndex(0);
        jHRate3.setSelectedIndex(0);
        jHRate4.setSelectedIndex(0);
        jHRate5.setSelectedIndex(0);
        
        jOverTime1.setSelectedIndex(0);
        jOverTime2.setSelectedIndex(0);
        jOverTime3.setSelectedIndex(0);
        jOverTime4.setSelectedIndex(0);
        jOverTime5.setSelectedIndex(0);
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       double sumUp1, sumUp2, sumUp3, sumUp4, sumUp5, sumUp6, sumUp7, sumUp8, sumUp9, sumUp10, sumUp11, sumUp12, sumUp13, sumUp14, sumUp15, sumUp16, sumUp17, sumUp18, sumUp19, sumUp20, sumUp21, sumUp22, sumUp23, sumUp24, sumUp25, sumUp26, sumUp27, sumUp28, sumUp29, sumUp30, sumUp31, sumUp32, sumUp33, sumUp34, sumUp35, sumUp36, sumUp37, sumUp38, sumUp39, sumUp40, sumUp41, sumUp42, sumUp43, sumUp44, sumUp45, sumUp46, sumUp47, sumUp48, sumUp49, sumUp50, sumUp51, sumUp52, sumUp53, sumUp54, sumUp55, sumUp56, sumUp57, sumUp58, sumUp59, sumUp60; 
        
       double R1Answer1, R2Answer1, R3Answer1, R4Answer1, R1Answer2, R2Answer2, R3Answer2, R4Answer2, R1Answer3, R2Answer3, R3Answer3, R4Answer3, R1Answer4, R2Answer4, R3Answer4, R4Answer4, R1Answer5, R2Answer5, R3Answer5, R4Answer5;
       
        try {
            
            if(jRadMon.isSelected())
            {
                
                hour1 = Double.parseDouble(jTimeIn1.getText());
                hour2 = Double.parseDouble(jTimeOut1.getText());
                Totalhour1 = (hour2-hour1)/24;
                Totalhour1 = (Totalhour1 * 24 );
                String result = String.format("%.2f",Totalhour1);
                jHW1.setText(result);
                
                String HR1 = jHRate1.getSelectedItem().toString();
                String HR2 = jOverTime1.getSelectedItem().toString();
                hour3 = Double.parseDouble(HR1);    
                hour4 = Double.parseDouble(HR2);
                R1Answer1 = ((Totalhour1 * hour3)+(hour3 * hour4));
                String rest4 = String.format("%.2f",R1Answer1);
                jMon1.setText(rest4);
                jWages1.setText(rest4);
                
                
                //monday row 2 
                
                hour5 = Double.parseDouble(jTimeIn2.getText());
                hour6 = Double.parseDouble(jTimeOut2.getText());
                Totalhour2 = (hour6-hour5)/24;
                Totalhour2 = (Totalhour2 * 24 );
                String row2 = String.format("%.2f",Totalhour2);
                jHW2.setText(row2);
                
                String RowR1 = jHRate2.getSelectedItem().toString();
                String RowR2 = jOverTime2.getSelectedItem().toString();
                hour7 = Double.parseDouble(RowR1);
                hour8 = Double.parseDouble(RowR2);
                R1Answer2 = ((Totalhour2 * hour7)+(hour7 * hour8));
                String resultrow2 = String.format("%.2f",R1Answer2);
                jMon2.setText(resultrow2);
                jWages2.setText(resultrow2);
                
                //monday row 3
                
                hour9 = Double.parseDouble(jTimeIn3.getText());
                hour10 = Double.parseDouble(jTimeOut3.getText());
                Totalhour3 = (hour10-hour9)/24;
                Totalhour3 = (Totalhour3 * 24 );
                String Mrow2 = String.format("%.2f",Totalhour3);
                jHW3.setText(Mrow2);
                
                String MRowR1 = jHRate2.getSelectedItem().toString();
                String MRowR2 = jOverTime2.getSelectedItem().toString();
                hour11 = Double.parseDouble(MRowR1);
                hour12 = Double.parseDouble(MRowR2);
                R1Answer3 = ((Totalhour3 * hour11)+(hour11 * hour12));
                String resultrow3 = String.format("%.2f",R1Answer3);
                jMon3.setText(resultrow3);
                jWages3.setText(resultrow3);
                
                //Monday row 4
                
                hour13 = Double.parseDouble(jTimeIn4.getText());
                hour14 = Double.parseDouble(jTimeOut4.getText());
                Totalhour4 = (hour14-hour13)/24;
                Totalhour4 = (Totalhour4 * 24 );
                String Mrow4 = String.format("%.2f",Totalhour4);
                jHW4.setText(Mrow4);
                
                String MRow4R1 = jHRate2.getSelectedItem().toString();
                String MRow4R2 = jOverTime2.getSelectedItem().toString();
                hour15 = Double.parseDouble(MRow4R1);
                hour16 = Double.parseDouble(MRow4R2);
                R1Answer4 = ((Totalhour4 * hour15)+(hour15 * hour16));
                String resurow4 = String.format("%.2f",R1Answer4);
                jMon4.setText(resurow4);
                jWages4.setText(resurow4);
                
                //monday row5
                
                hour17 = Double.parseDouble(jTimeIn4.getText());
                hour18 = Double.parseDouble(jTimeOut4.getText());
                Totalhour5 = (hour18-hour17)/24;
                Totalhour5 = (Totalhour5 * 24 );
                String Mrow5 = String.format("%.2f",Totalhour5);
                jHW5.setText(Mrow5);
                
                String MRow5R1 = jHRate2.getSelectedItem().toString();
                String MRow5R2 = jOverTime2.getSelectedItem().toString();
                hour19 = Double.parseDouble(MRow5R1);
                hour20 = Double.parseDouble(MRow5R2);
                R1Answer5 = ((Totalhour5 * hour19)+(hour19 * hour20));
                String resultrow5 = String.format("%.2f",R1Answer5);
                jMon5.setText(resultrow5);
                jWages5.setText(resultrow5);
            
                    }
            else if(jRadTue.isSelected()){
                
                sumUp1 = Double.parseDouble(jWages1.getText());
                jWages1.setText(null);
                hour21=Double.parseDouble(jTimeIn1.getText());
                hour22=Double.parseDouble(jTimeOut1.getText());
                Totalhour6 = (hour22 - hour21)/24;
                Totalhour6 = (Totalhour6 * 24);
                String Tueresult= String.format("%.2f",Totalhour6);
                jHW1.setText(Tueresult);
                
                String HR3 = jHRate1.getSelectedItem().toString();
                String HR4 = jOverTime1.getSelectedItem().toString();
                hour23 = Double.parseDouble(HR3);
                hour24 = Double.parseDouble(HR4);
                R2Answer1 = ((Totalhour6 * hour23)+(hour23*hour24));
                String Tueresult1 = String.format("%.2f",R2Answer1);
                jTue1.setText(Tueresult1);
                
                //Add to wages
                sumUp2=Double.parseDouble(jTue1.getText());
                String Tueresultla = String.format("%.2f",sumUp2);
                jWages1.setText(Tueresultla);
                sumUp3 = sumUp1 + sumUp2;
                String Tueresultlb = String.format("%.2f",sumUp3);
                jWages1.setText(Tueresultlb);
                
                //Tue Row 2
                
                
                sumUp7 = Double.parseDouble(jWages2.getText());
                jWages2.setText(null);
                hour25=Double.parseDouble(jTimeIn2.getText());
                hour26=Double.parseDouble(jTimeOut2.getText());
                Totalhour7 = (hour26 - hour25)/24;
                Totalhour7 = (Totalhour7 * 24);
                String row2= String.format("%.2f",Totalhour7);
                jHW2.setText(row2);
                
                String RowTueR1 = jHRate2.getSelectedItem().toString();
                String RowTueR2 = jOverTime2.getSelectedItem().toString();
                hour27 = Double.parseDouble(RowTueR1);
                hour28 = Double.parseDouble(RowTueR2);
                R2Answer2 = ((Totalhour7 * hour27)+(hour27 * hour28));
                String resulttuerow2 = String.format("%.2f",R2Answer2);
                jTue2.setText(resulttuerow2);
                jWages2.setText(resulttuerow2);
                //Add to wages
                sumUp8=Double.parseDouble(jTue2.getText());
                String Tueresultlc = String.format("%.2f",sumUp8);
                jWages1.setText(Tueresultlc);
                sumUp9 = sumUp8 + sumUp7;
                String Tueresultld = String.format("%.2f",sumUp9);
                jWages2.setText(Tueresultld);
                
                //Tue Row 3
                
                sumUp10 = Double.parseDouble(jWages3.getText());
                jWages3.setText(null);
                hour29=Double.parseDouble(jTimeIn3.getText());
                hour30=Double.parseDouble(jTimeOut3.getText());
                Totalhour8 = (hour30 - hour29)/24;
                Totalhour8 = (Totalhour8 * 24);
                String row3= String.format("%.2f",Totalhour8);
                jHW3.setText(row3);
                
                String Row3TueR1 = jHRate3.getSelectedItem().toString();
                String Row3TueR2 = jOverTime3.getSelectedItem().toString();
                hour31 = Double.parseDouble(Row3TueR1);
                hour32 = Double.parseDouble(Row3TueR2);
                R2Answer3 = ((Totalhour8 * hour31)+(hour31 * hour32));
                String resulttuerow3 = String.format("%.2f",R2Answer3);
                jTue3.setText(resulttuerow3);
                jWages3.setText(resulttuerow3);
                //Add to wages
                sumUp11=Double.parseDouble(jTue3.getText());
                String Tueresultle = String.format("%.2f",sumUp11);
                jWages3.setText(Tueresultle);
                sumUp12 = sumUp11 + sumUp10;
                String Tueresultlf = String.format("%.2f",sumUp12);
                jWages3.setText(Tueresultlf);
                
            
                
                //tue row 4
                sumUp13 = Double.parseDouble(jWages4.getText());
                jWages4.setText(null);
                hour33=Double.parseDouble(jTimeIn4.getText());
                hour34=Double.parseDouble(jTimeOut4.getText());
                Totalhour9 = (hour34 - hour33)/24;
                Totalhour9 = (Totalhour9 * 24);
                String pk= String.format("%.2f",Totalhour9);
                jHW4.setText(pk);
                
                String Row4TueR1 = jHRate4.getSelectedItem().toString();
                String Row4TueR2 = jOverTime4.getSelectedItem().toString();
                hour35 = Double.parseDouble(Row4TueR1);
                hour36 = Double.parseDouble(Row4TueR2);
                R2Answer4 = ((Totalhour9 * hour35)+(hour35 * hour36));
                String re4 = String.format("%.2f",R2Answer4);
                jTue4.setText(re4);
                jWages4.setText(re4);
                //Add to wages
                sumUp14=Double.parseDouble(jTue4.getText());
                String Tg = String.format("%.2f",sumUp14);
                jWages4.setText(Tg);
                sumUp15 = sumUp14 + sumUp13;
                String Tltlh = String.format("%.2f",sumUp15);
                jWages4.setText(Tltlh);
                
                
                //tue row 5
                
              
                sumUp16 = Double.parseDouble(jWages5.getText());
                jWages5.setText(null);
                hour37=Double.parseDouble(jTimeIn5.getText());
                hour38=Double.parseDouble(jTimeOut5.getText());
                Totalhour10 = (hour38 - hour37)/24;
                Totalhour10 = (Totalhour10 * 24);
                String row5= String.format("%.2f",Totalhour10);
                jHW5.setText(row5);
                
                String Row5TueR1 = jHRate5.getSelectedItem().toString();
                String Row5TueR2 = jOverTime5.getSelectedItem().toString();
                hour39 = Double.parseDouble(Row5TueR1);
                hour40 = Double.parseDouble(Row5TueR2);
                R2Answer5 = ((Totalhour10 * hour39)+(hour39 * hour40));
                String resulttuerow5 = String.format("%.2f",R2Answer5);
                jTue5.setText(resulttuerow5);
                jWages5.setText(resulttuerow5);
                //Add to wages
                sumUp17=Double.parseDouble(jTue5.getText());
                String Tueresultli = String.format("%.2f",sumUp14);
                jWages5.setText(Tueresultli);
                sumUp19 = sumUp16 + sumUp17;
                String Tueresultlj = String.format("%.2f",sumUp19);
                jWages5.setText(Tueresultlj);
                 
            }
            else if(jRadWed.isSelected())
            {
                
                //Wed row 1
                
                sumUp4=Double.parseDouble(jWages1.getText());
                jWages1.setText(null);
                hour1 = Double.parseDouble(jTimeIn1.getText());
                hour2 = Double.parseDouble(jTimeOut1.getText());
                Totalhour11 = (hour2-hour1)/24;
                Totalhour11 = (Totalhour11 * 24 );
                String Wedresult = String.format("%.2f",Totalhour11);
                jHW1.setText(Wedresult);
                
                String HR3 = jHRate1.getSelectedItem().toString();
                String HR4 = jOverTime1.getSelectedItem().toString();
                hour7 = Double.parseDouble(HR3);
                hour8 = Double.parseDouble(HR4);
                R3Answer1 = ((Totalhour11 * hour7)+(hour7 * hour8));
                String result3 = String.format("%.2f",R3Answer1);
                //jMon1.setText(result4);
                jWed1.setText(result3);
                
                 //Add to wages
                sumUp5=Double.parseDouble(jWed1.getText());
                String Wedresultla = String.format("%.2f",sumUp5);
                jWages1.setText(Wedresultla);
                sumUp6 = sumUp4 + sumUp5;
                String Tueresultlb = String.format("%.2f",sumUp6);
                jWages1.setText(Tueresultlb);
                
                
                
                //Wed row 2
                
                sumUp20=Double.parseDouble(jWages2.getText());
                jWages2.setText(null);
                hour41 = Double.parseDouble(jTimeIn2.getText());
                hour42 = Double.parseDouble(jTimeOut2.getText());
                Totalhour11 = (hour42-hour41)/24;
                Totalhour11 = (Totalhour11 * 24 );
                String Wedrow2 = String.format("%.2f",Totalhour11);
                jHW2.setText(Wedrow2);
                
                String H3Row3 = jHRate2.getSelectedItem().toString();
                String H3Row4 = jOverTime2.getSelectedItem().toString();
                hour43 = Double.parseDouble(H3Row3);
                hour44 = Double.parseDouble(H3Row4);
                R3Answer2 = ((Totalhour11 * hour43)+(hour43 * hour44));
                String Wedresult2 = String.format("%.2f",R3Answer2);
                //jMon1.setText(result4);
                jWed2.setText(Wedresult2);
                
                 //Add to wages
                sumUp21=Double.parseDouble(jWed2.getText());
                String Wed2resultla = String.format("%.2f",sumUp21);
                jWages2.setText(Wed2resultla);
                sumUp22 = sumUp20 + sumUp21;
                String Wed2resultlb = String.format("%.2f",sumUp22);
                jWages2.setText(Wed2resultlb);
                
                
                //Wed row 3
                
                sumUp23=Double.parseDouble(jWages3.getText());
                jWages3.setText(null);
                hour45 = Double.parseDouble(jTimeIn3.getText());
                hour46 = Double.parseDouble(jTimeOut3.getText());
                Totalhour12 = (hour46-hour45)/24;
                Totalhour12 = (Totalhour12 * 24 );
                String Wedrow3 = String.format("%.2f",Totalhour12);
                jHW3.setText(Wedrow3);
                
                String H3Row33 = jHRate3.getSelectedItem().toString();
                String H3Row34 = jOverTime3.getSelectedItem().toString();
                hour47 = Double.parseDouble(H3Row33);
                hour48 = Double.parseDouble(H3Row34);
                R3Answer3 = ((Totalhour11 * hour43)+(hour43 * hour44));
                String Wedresult3 = String.format("%.2f",R3Answer3);
                //jMon1.setText(result4);
                jWed3.setText(Wedresult3);
                
                 //Add to wages
                sumUp24=Double.parseDouble(jWed3.getText());
                String Wed3resultla = String.format("%.2f",sumUp24);
                jWages3.setText(Wed3resultla);
                sumUp25 = sumUp23 + sumUp24;
                String Wed3resultlb = String.format("%.2f",sumUp25);
                jWages3.setText(Wed3resultlb);
                
                //wed 4 row
                
                sumUp26=Double.parseDouble(jWages4.getText());
                jWages4.setText(null);
                hour49 = Double.parseDouble(jTimeIn4.getText());
                hour50 = Double.parseDouble(jTimeOut4.getText());
                Totalhour13 = (hour50-hour49)/24;
                Totalhour13 = (Totalhour13 * 24 );
                String Wedrow4 = String.format("%.2f",Totalhour13);
                jHW4.setText(Wedrow4);
                
                String H3Row43 = jHRate4.getSelectedItem().toString();
                String H3Row44 = jOverTime4.getSelectedItem().toString();
                hour51 = Double.parseDouble(H3Row43);
                hour52 = Double.parseDouble(H3Row44);
                R3Answer4 = ((Totalhour13 * hour51)+(hour51 * hour52));
                String Wedresult4 = String.format("%.2f",R3Answer4);
                //jMon1.setText(result4);
                jWed4.setText(Wedresult4);
                
                 //Add to wages
                sumUp27=Double.parseDouble(jWed4.getText());
                String Wed4resultla = String.format("%.2f",sumUp27);
                jWages4.setText(Wed4resultla);
                sumUp28 = sumUp26 + sumUp27;
                String Wed4resultlb = String.format("%.2f",sumUp28);
                jWages4.setText(Wed4resultlb);
                
                
                //wed 5 row
                
                sumUp29=Double.parseDouble(jWages5.getText());
                jWages5.setText(null);
                hour53 = Double.parseDouble(jTimeIn5.getText());
                hour54 = Double.parseDouble(jTimeOut5.getText());
                Totalhour14 = (hour54-hour53)/24;
                Totalhour14 = (Totalhour14 * 24 );
                String Wedrow5 = String.format("%.2f",Totalhour14);
                jHW5.setText(Wedrow5);
                
                String H3Row53 = jHRate5.getSelectedItem().toString();
                String H3Row54 = jOverTime5.getSelectedItem().toString();
                hour55 = Double.parseDouble(H3Row53);
                hour56 = Double.parseDouble(H3Row54);
                R3Answer5 = ((Totalhour14 * hour55)+(hour55 * hour56));
                String Wedresult5 = String.format("%.2f",R3Answer5);
                //jMon1.setText(result4);
                jWed5.setText(Wedresult5);
                
                 //Add to wages
                sumUp30=Double.parseDouble(jWed5.getText());
                String Wed5resultla = String.format("%.2f",sumUp30);
                jWages5.setText(Wed5resultla);
                sumUp31 = sumUp30 + sumUp29;
                String Wed5resultlb = String.format("%.2f",sumUp31);
                jWages5.setText(Wed5resultlb);
                
               
            }            
            
            
            
            else if(jRadThru.isSelected())
            {
                
                //thru row 1
                
                sumUp32=Double.parseDouble(jWages1.getText());
                jWages1.setText(null);
                hour57 = Double.parseDouble(jTimeIn1.getText());
                hour58 = Double.parseDouble(jTimeOut1.getText());
                Totalhour15 = (hour58-hour57)/24;
                Totalhour15 = (Totalhour11 * 24 );
                String Thurresult = String.format("%.2f",Totalhour15);
                jHW1.setText(Thurresult);
                
                String HR443 = jHRate1.getSelectedItem().toString();
                String HR444 = jOverTime1.getSelectedItem().toString();
                hour59 = Double.parseDouble(HR443);
                hour60 = Double.parseDouble(HR444);
                R4Answer1 = ((Totalhour15 * hour59)+(hour59 * hour60));
                String Thurresult4 = String.format("%.2f",R4Answer1);
                //jMon1.setText(result4);
                jThru1.setText(Thurresult4);
                
                 //Add to wages
                sumUp33=Double.parseDouble(jThru1.getText());
                String Thurresult14a = String.format("%.2f",sumUp33);
                jWages1.setText(Thurresult14a);
                sumUp34 = sumUp32 + sumUp33;
                String Tureresult4b = String.format("%.2f",sumUp34);
                jWages1.setText(Tureresult4b);
                
                
            //thru row 2
                
                sumUp35=Double.parseDouble(jWages2.getText());
                jWages2.setText(null);
                hour61 = Double.parseDouble(jTimeIn2.getText());
                hour62 = Double.parseDouble(jTimeOut2.getText());
                Totalhour16 = (hour62-hour61)/24;
                Totalhour16 = (Totalhour16 * 24 );
                String Thurrow2 = String.format("%.2f",Totalhour16);
                jHW2.setText(Thurrow2);
                
                String H4Row3 = jHRate2.getSelectedItem().toString();
                String H4Row4 = jOverTime2.getSelectedItem().toString();
                hour63 = Double.parseDouble(H4Row3);
                hour64 = Double.parseDouble(H4Row4);
                R4Answer2 = ((Totalhour16 * hour63)+(hour63 * hour64));
                String Thurresult2 = String.format("%.2f",R4Answer2);
                //jMon1.setText(result4);
                jThru2.setText(Thurresult2);
                
                 //Add to wages
                sumUp36=Double.parseDouble(jThru2.getText());
                String Thurresult1a = String.format("%.2f",sumUp36);
                jWages2.setText(Thurresult1a);
                sumUp37 = sumUp35 + sumUp36;
                String Tuer4result2bb = String.format("%.2f",sumUp34);
                jWages2.setText(Tuer4result2bb);
            
             
            //thru row 3
                
                sumUp38=Double.parseDouble(jWages3.getText());
                jWages3.setText(null);
                hour65 = Double.parseDouble(jTimeIn3.getText());
                hour66 = Double.parseDouble(jTimeOut3.getText());
                Totalhour17 = (hour66-hour65)/24;
                Totalhour17 = (Totalhour17 * 24 );
                String Thurrow3 = String.format("%.2f",Totalhour17);
                jHW3.setText(Thurrow3);
                
                String H3Row33 = jHRate3.getSelectedItem().toString();
                String H3Row34 = jOverTime3.getSelectedItem().toString();
                hour67 = Double.parseDouble(H3Row33);
                hour68 = Double.parseDouble(H3Row34);
                R4Answer3 = ((Totalhour17 * hour67)+(hour67 * hour68));
                String Thurresult3 = String.format("%.2f",R4Answer3);
                //jMon1.setText(result4);
                jThru3.setText(Thurresult3);
                
                 //Add to wages
                sumUp39=Double.parseDouble(jThru3.getText());
                String Thur3result1a = String.format("%.2f",sumUp39);
                jWages3.setText(Thur3result1a);
                sumUp40 = sumUp38 + sumUp39;
                String Tuer3result1bb = String.format("%.2f",sumUp40);
                jWages3.setText(Tuer3result1bb);
            
            
            //thru row 4
                
                sumUp41=Double.parseDouble(jWages4.getText());
                jWages4.setText(null);
                hour69 = Double.parseDouble(jTimeIn4.getText());
                hour70 = Double.parseDouble(jTimeOut4.getText());
                Totalhour18 = (hour70-hour69)/24;
                Totalhour18 = (Totalhour18 * 24 );
                String Thurrow4 = String.format("%.2f",Totalhour18);
                jHW4.setText(Thurrow4);
                
                String H3Row43 = jHRate4.getSelectedItem().toString();
                String H3Row44 = jOverTime4.getSelectedItem().toString();
                hour71 = Double.parseDouble(H3Row43);
                hour72 = Double.parseDouble(H3Row44);
                R4Answer4 = ((Totalhour18 * hour71)+(hour71 * hour72));
                String Thurresult4a = String.format("%.2f",R4Answer4);
                //jMon1.setText(result4);
                jThru4.setText(Thurresult4a);
                
                 //Add to wages
                sumUp42=Double.parseDouble(jThru4.getText());
                String Thur4result1 = String.format("%.2f",sumUp42);
                jWages4.setText(Thur4result1);
                sumUp43 = sumUp41 + sumUp42;
                String Tuer4resultld = String.format("%.2f",sumUp43);
                jWages4.setText(Tuer4resultld);
            
            
            
            //thru row 5
                
                sumUp44=Double.parseDouble(jWages5.getText());
                jWages5.setText(null);
                hour73 = Double.parseDouble(jTimeIn5.getText());
                hour74 = Double.parseDouble(jTimeOut5.getText());
                Totalhour19 = (hour74-hour73)/24;
                Totalhour19 = (Totalhour19 * 24 );
                String Thurrow5 = String.format("%.2f",Totalhour19);
                jHW5.setText(Thurrow5);
                
                String H4Row53 = jHRate5.getSelectedItem().toString();
                String H4Row54 = jOverTime5.getSelectedItem().toString();
                hour75 = Double.parseDouble(H4Row53);
                hour76 = Double.parseDouble(H4Row54);
                R4Answer5 = ((Totalhour19 * hour75)+(hour75 * hour76));
                String Thurresult5 = String.format("%.2f",R4Answer5);
                //jMon1.setText(result4);
                jThru5.setText(Thurresult5);
                
                 //Add to wages
                sumUp45=Double.parseDouble(jThru5.getText());
                String Thur4result1a = String.format("%.2f",sumUp45);
                jWages5.setText(Thur4result1a);
                sumUp46 = sumUp44 + sumUp45;
                String Tuer5resultld = String.format("%.2f",sumUp46);
                jWages5.setText(Tuer5resultld);
            
            
            }
            
            else if(jRadFri.isSelected())
            {
                
                //fri row 1 row 1
                
                sumUp47=Double.parseDouble(jWages1.getText());
                jWages1.setText(null);
                hour77 = Double.parseDouble(jTimeIn1.getText());
                hour78 = Double.parseDouble(jTimeOut1.getText());
                Totalhour20 = (hour78-hour77)/24;
                Totalhour20 = (Totalhour20 * 24 );
                String Friresult = String.format("%.2f",Totalhour20);
                jHW1.setText(Friresult);
                
                String HR443 = jHRate1.getSelectedItem().toString();
                String HR444 = jOverTime1.getSelectedItem().toString();
                hour79 = Double.parseDouble(HR443);
                hour80 = Double.parseDouble(HR444);
                R4Answer1 = ((Totalhour20 * hour79)+(hour79 * hour80));
                String Thurresult4 = String.format("%.2f",R4Answer1);
                //jMon1.setText(result4);
                jFri1.setText(Thurresult4);
                
                 //Add to wages
                sumUp48=Double.parseDouble(jFri1.getText());
                String Thurresult14a = String.format("%.2f",sumUp48);
                jWages1.setText(Thurresult14a);
                sumUp49 = sumUp47 + sumUp48;
                String Friresult4b = String.format("%.2f",sumUp49);
                jWages1.setText(Friresult4b);
                
                
            //thru row 2
                
                sumUp50=Double.parseDouble(jWages2.getText());
                jWages2.setText(null);
                hour81 = Double.parseDouble(jTimeIn2.getText());
                hour82 = Double.parseDouble(jTimeOut2.getText());
                Totalhour21 = (hour82-hour81)/24;
                Totalhour21 = (Totalhour21 * 24 );
                String Frirow2 = String.format("%.2f",Totalhour21);
                jHW2.setText(Frirow2);
                
                String H4Row3 = jHRate2.getSelectedItem().toString();
                String H4Row4 = jOverTime2.getSelectedItem().toString();
                hour83 = Double.parseDouble(H4Row3);
                hour84 = Double.parseDouble(H4Row4);
                R4Answer2 = ((Totalhour21 * hour83)+(hour83 * hour84));
                String Friresult2 = String.format("%.2f",R4Answer2);
                //jMon1.setText(result4);
                jFri2.setText(Friresult2);
                
                 //Add to wages
                sumUp51=Double.parseDouble(jFri2.getText());
                String Fri2result1a = String.format("%.2f",sumUp51);
                jWages1.setText(Fri2result1a);
                sumUp52 = sumUp51 + sumUp50;
                String Tue4result2bb = String.format("%.2f",sumUp52);
                jWages2.setText(Tue4result2bb);
            
             
            //thru row 3
                
                sumUp53=Double.parseDouble(jWages3.getText());
                jWages3.setText(null);
                hour85 = Double.parseDouble(jTimeIn3.getText());
                hour86 = Double.parseDouble(jTimeOut3.getText());
                Totalhour22 = (hour86-hour85)/24;
                Totalhour22 = (Totalhour22 * 24 );
                String Trrow3 = String.format("%.2f",Totalhour22);
                jHW3.setText(Trrow3);
                
                String H3Row33 = jHRate3.getSelectedItem().toString();
                String H3Row34 = jOverTime3.getSelectedItem().toString();
                hour87 = Double.parseDouble(H3Row33);
                hour88 = Double.parseDouble(H3Row34);
                R4Answer3 = ((Totalhour22 * hour87)+(hour87 * hour88));
                String Thuresult3 = String.format("%.2f",R4Answer3);
                //jMon1.setText(result4);
                jFri3.setText(Thuresult3);
                
                 //Add to wages
                sumUp54=Double.parseDouble(jFri3.getText());
                String Friesult1a = String.format("%.2f",sumUp54);
                jWages3.setText(Friesult1a);
                sumUp55 = sumUp53 + sumUp54;
                String Fri3re= String.format("%.2f",sumUp55);
                jWages3.setText(Fri3re);
            
            
            //thru row 4
                
                sumUp56=Double.parseDouble(jWages4.getText());
                jWages4.setText(null);
                hour89 = Double.parseDouble(jTimeIn4.getText());
                hour90 = Double.parseDouble(jTimeOut4.getText());
                Totalhour23 = (hour90-hour89)/24;
                Totalhour23 = (Totalhour23 * 24 );
                String Frirow4 = String.format("%.2f",Totalhour23);
                jHW4.setText(Frirow4);
                
                String H3Row43 = jHRate4.getSelectedItem().toString();
                String H3Row44 = jOverTime4.getSelectedItem().toString();
                hour91 = Double.parseDouble(H3Row43);
                hour92 = Double.parseDouble(H3Row44);
                R4Answer4 = ((Totalhour23 * hour91)+(hour91 * hour92));
                String Tesult4a = String.format("%.2f",R4Answer4);
                //jMon1.setText(result4);
                jFri4.setText(Tesult4a);
                
                 //Add to wages
                sumUp57=Double.parseDouble(jFri4.getText());
                String t1 = String.format("%.2f",sumUp57);
                jWages4.setText(t1);
                sumUp58 = sumUp57 + sumUp56;
                String d = String.format("%.2f",sumUp58);
                jWages4.setText(d);
            
            
            
            //thru row 5
                
                sumUp58=Double.parseDouble(jWages5.getText());
                jWages5.setText(null);
                hour93 = Double.parseDouble(jTimeIn5.getText());
                hour94 = Double.parseDouble(jTimeOut5.getText());
                Totalhour24 = (hour94-hour93)/24;
                Totalhour24 = (Totalhour24 * 24 );
                String rrow5 = String.format("%.2f",Totalhour24);
                jHW5.setText(rrow5);
                
                String H4Row53 = jHRate5.getSelectedItem().toString();
                String H4Row54 = jOverTime5.getSelectedItem().toString();
                hour95 = Double.parseDouble(H4Row53);
                hour96 = Double.parseDouble(H4Row54);
                R4Answer5 = ((Totalhour24 * hour95)+(hour95 * hour96));
                String rlt5 = String.format("%.2f",R4Answer5);
                //jMon1.setText(result4);
                jFri5.setText(rlt5);
                
                 //Add to wages
                sumUp59=Double.parseDouble(jFri5.getText());
                String T1a = String.format("%.2f",sumUp59);
                jWages5.setText(T1a);
                sumUp60 = sumUp58 + sumUp59;
                String tlgd = String.format("%.2f",sumUp60);
                jWages5.setText(tlgd);
           
        }
        }
        catch(NumberFormatException e)
                {
                    JOptionPane.showMessageDialog(null,"Enter a valid Number ","Just Numbes",JOptionPane.INFORMATION_MESSAGE);
                    jTimeIn1.requestFocus();
                }
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimeTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jFri1;
    private javax.swing.JLabel jFri2;
    private javax.swing.JLabel jFri3;
    private javax.swing.JLabel jFri4;
    private javax.swing.JLabel jFri5;
    private javax.swing.JComboBox<String> jHRate1;
    private javax.swing.JComboBox<String> jHRate2;
    private javax.swing.JComboBox<String> jHRate3;
    private javax.swing.JComboBox<String> jHRate4;
    private javax.swing.JComboBox<String> jHRate5;
    private javax.swing.JLabel jHW1;
    private javax.swing.JLabel jHW2;
    private javax.swing.JLabel jHW3;
    private javax.swing.JLabel jHW4;
    private javax.swing.JLabel jHW5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jMon1;
    private javax.swing.JLabel jMon2;
    private javax.swing.JLabel jMon3;
    private javax.swing.JLabel jMon4;
    private javax.swing.JLabel jMon5;
    private javax.swing.JComboBox<String> jOverTime1;
    private javax.swing.JComboBox<String> jOverTime2;
    private javax.swing.JComboBox<String> jOverTime3;
    private javax.swing.JComboBox<String> jOverTime4;
    private javax.swing.JComboBox<String> jOverTime5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadFri;
    private javax.swing.JRadioButton jRadMon;
    private javax.swing.JRadioButton jRadThru;
    private javax.swing.JRadioButton jRadTue;
    private javax.swing.JRadioButton jRadWed;
    private javax.swing.JLabel jThru1;
    private javax.swing.JLabel jThru2;
    private javax.swing.JLabel jThru3;
    private javax.swing.JLabel jThru4;
    private javax.swing.JLabel jThru5;
    private javax.swing.JTextField jTimeIn1;
    private javax.swing.JTextField jTimeIn2;
    private javax.swing.JTextField jTimeIn3;
    private javax.swing.JTextField jTimeIn4;
    private javax.swing.JTextField jTimeIn5;
    private javax.swing.JTextField jTimeOut1;
    private javax.swing.JTextField jTimeOut2;
    private javax.swing.JTextField jTimeOut3;
    private javax.swing.JTextField jTimeOut4;
    private javax.swing.JTextField jTimeOut5;
    private javax.swing.JLabel jTue1;
    private javax.swing.JLabel jTue2;
    private javax.swing.JLabel jTue3;
    private javax.swing.JLabel jTue4;
    private javax.swing.JLabel jTue5;
    private javax.swing.JLabel jWages1;
    private javax.swing.JLabel jWages2;
    private javax.swing.JLabel jWages3;
    private javax.swing.JLabel jWages4;
    private javax.swing.JLabel jWages5;
    private javax.swing.JLabel jWed1;
    private javax.swing.JLabel jWed2;
    private javax.swing.JLabel jWed3;
    private javax.swing.JLabel jWed4;
    private javax.swing.JLabel jWed5;
    private javax.swing.JLabel jlblWages;
    // End of variables declaration//GEN-END:variables
}
